### ISSUE TITLE
Can't create app using npm or yarn

### ISSUE THREAD

**Issue by Shqrp** [Khaaz/create-axoncore-app#7]
Hello Khaazz,
I wanted to tell you that when I do `yarn create axoncore-app -l eris -t esm .\src\` it works but it doesn't install it in the chosen folder, but instead in the Local AppData folder of yarn. I tried this even with npm and npx but nothing, always in the Local AppData. I even tried running the cli.js script in the folder, but it doesn't work.

**Comment by bsian03** [comment]
Hi there, 
We removed selecting which directory the axoncore project will be installed in, so there's no need to supply a directory
I'm still finding a solution to the application not installing in the correct folder, thanks for letting me know what's happening though.

**Comment by Khaaz** [comment]
It should indeed install in the current directory. We are still investigating atm, and we will come back to you here when we are sure what is the issue and what is the potential fix.
As a side note, we will also probably add back choosing directory as first argument. Not providing a path would still install in current directory whatsoever.

I hope this is not too much of a blocking issue for you, be sure we are looking into why this could happen!

**Comment by Khaaz** [comment]
Was fixed in v2.0.2 (d2fee79e54cbbadef21adefb59c5358943040282). 
#8 will add back optional installing path (as first argument). Not providing any will install in the current directory.

It seems to also works with yarn as well which is a good news. Will close this issue and #8 get merged.
Thanks for the report, this was indeed not working propertly 👍
